version: "3.8"
services:
  server:
    depends_on:
      - db
    ports:
      - "8080:8080"
    container_name: server
    image: greenisha/quiz_bot:server
    build:
      context: ./server
    environment:
      RESTAPI: ${RESTAPI}
      API_KEY: ${API_KEY}
    networks:
      - mynet
  rest:
    depends_on:
      - db
    ports:
      - "8000:8001"
    container_name: rest-server
    image: greenisha/quiz_bot:rest
    build:
      context: ./rest
    environment:
      POSTGRES_DB: ${PGDB:-testdb}
      POSTGRES_USER: ${PGUSER:-pguser}
      POSTGRES_PASSWORD: ${PGUSER:-pgpass}  
      POSTGRES_HOST: ${PGHOST:-db}  
      POSTGRES_PORT: ${PGPORT:-5432}  
    networks:
      - mynet
  db:
    ports:
      - "5432:5432"
    build:
      context: ./db
    image: greenisha/quiz_bot:db
    environment:
      POSTGRES_DB: ${PGDB:-testdb}
      POSTGRES_USER: ${PGUSER:-pguser}
      POSTGRES_PASSWORD: ${PGPASSWORD:-pgpass}
      POSTGRES_HOST: ${PGHOST:-db}  
      POSTGRES_PORT: ${PGPORT:-5432}  
    networks:
        - mynet
  front:
    ports:
      - "80:80"
    build:
      context: ./front
    image: greenisha/quiz_bot:front
    networks:
        - mynet

networks:
  mynet:
    driver: bridge